# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-24 22:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField(default=0)),
                ('curso', models.CharField(max_length=200)),
                ('renda', models.CharField(max_length=200)),
                ('residencia', models.TextField()),
                ('quantos_km', models.IntegerField(default=0)),
                ('renda_familiar', models.IntegerField(default=0)),
                ('ja_possui_graducao', models.BooleanField(default=False)),
                ('ja_possui_tecnico', models.BooleanField(default=False)),
                ('curso_em_andamento', models.BooleanField(default=False)),
                ('data_resposta', models.DateTimeField(default=django.utils.timezone.now)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Graduacao_fazendo_tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_curso', models.IntegerField(default=0)),
                ('fim_curso', models.IntegerField(default=0)),
                ('data_resposta', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evasion.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico_fazendo_graducacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_curso', models.IntegerField(default=0)),
                ('fim_curso', models.IntegerField(default=0)),
                ('data_resposta', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evasion.Aluno')),
            ],
        ),
    ]
