# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-28 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evasion', '0002_inscricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
